[package]
name = "maze"
version = "0.1.0"
authors = ["sharknasuhorse <nakaryo6459shark@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"